### ISSUE TITLE
font face : name & institute

### ISSUE THREAD

**Issue by pushpdeep** [shubhampk37/shubhampk37.github.io#3]
below photo : 
Name : Poppins font (16 px ), 
Institute Name : Open Sans ( 14 px )

**Comment by shubhampk37** [comment]
![Font-size](https://user-images.githubusercontent.com/61788363/82122904-fd219c80-97b3-11ea-8bb5-373a3d1ea107.png)
@pushpdeep Sir this is what I was trying to say today earlier.If the font-size of the the name is chosen as 16px; some longer names wrap up to the next line.So, in this case if we still want to use this font size then we'll have to increase the page size .
Also,see the lab concept conceptualization heading here.Is it fine or any changes?

**Comment by pushpdeep** [comment]
@shubhampk37  first try implementing CSS Grid . 

https://css-tricks.com/snippets/css/complete-guide-grid/
https://gridbyexample.com/examples/
it will make your life easier and its more professional to use Grids.

**Comment by shubhampk37** [comment]
@pushpdeep  I've pushed the file.I was unable to see your response,checked many times.I saw it just right now.I'll try with CSS grid now.

**Comment by pushpdeep** [comment]
Done
